Optimization and Leencode
automacon-trainee/AlexeyZem pull request #18
Opened 2024-08-19 11:47 UTC by Alexeyzem

2024-08-23 07:58 UTC, emildeev requested changes

2024-08-23 07:58 UTC, emildeev commented on course2/5.optimization/1.optimization_go/task2.5.1.1/internal/hash_map_list.go
> +	capacity int
capacity логичнее перенести в List

2024-08-23 07:58 UTC, emildeev commented on course2/5.optimization/1.optimization_go/task2.5.1.1/internal/hash_map_list.go
> +type List struct {
Вынеси логику листа в отдельный модуль, и добавь методы для работы с ним, либо используй container/list, из слайса тоже сделай модуль, суть в том что бы твоя хэш мапа и мела один кот и просто принимала интерфейс контейнера, и туда моно было подложить любой контейнер удовлетворяющий интерфейсу

2024-08-23 07:58 UTC, emildeev commented on course2/5.optimization/1.optimization_go/task2.5.1.1/internal/hash_map_list.go
> +	if 3*h.capacity <= h.length*4 {
Нужно вынести числа в константу что бы было понятно что они значат

2024-08-23 07:58 UTC, emildeev commented on course2/5.optimization/2.optimization_jsoniter/task2.5.2.1/model/user_easyjson.go
> +func easyjson9e1087fdEncodeJsointerModel(out *jwriter.Writer, in User) {
Что за странное название?

2024-08-23 07:58 UTC, emildeev commented on course2/5.optimization/2.optimization_jsoniter/task2.5.2.1/model/user_easyjson.go
> +var (
А зачем это?

2024-08-23 08:07 UTC, Alexeyzem commented on course2/5.optimization/2.optimization_jsoniter/task2.5.2.1/model/user_easyjson.go
> +func easyjson9e1087fdEncodeJsointerModel(out *jwriter.Writer, in User) {
Этот файл генерировался командой easyjson -all <file>.go 
Которая предоставляется в доке к пакету: https://github.com/mailru/easyjson

2024-09-06 07:53 UTC, emildeev commented on course2/5.optimization/1.optimization_go/task2.5.1.1/internal/hash_map_list.go
> +type List struct {
Модуль предполагает отдельную папку

2024-09-06 11:15 UTC, emildeev approved these changes

2024-09-06 11:15 UTC, merged